apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-credentials
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.credentials.username | b64enc | quote }}
  password: {{ .Values.credentials.password | b64enc | quote }}
  postgres-password: {{ .Values.credentials.postgresPassword | b64enc | quote }}
