name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          config: .cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Publish to GitHub Pages
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: .
          charts_url: https://${{ github.repository_owner }}.github.io/${{ github.repository_name }}
          owner: ${{ github.repository_owner }}
          git_email: 41898282+github-actions[bot]@users.noreply.github.com
